logging:
  level:
    io.example.asyncapi.shoppingcart: DEBUG
    org.apache.kafka.clients.admin: WARN

springdoc.swagger-ui.urls:
  - name: AsyncAPI Shopping Cart Example (Provider)
    url: /apis/openapi.yml

management:
  endpoints.web.exposure.include: "*"

app:
  kafka:
    topics:
      shopping-cart-channel:
        topic: shopping-cart

spring:
  security:
    user:
      name: admin
      password: password
      roles: USER
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      specific.avro.reader: true
      schema.registry.url: ${SCHEMA_REGISTRY_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}

  cloud:
    stream:
      kafka.binder.enable-observation: true
      function:
        definition: shopping-cart-channel
      bindings:
        shopping-cart-channel-out-0:
          destination: shopping-cart
          content-type: application/*+avro
          producer:
            use-native-encoding: true



