logging.level.org.hibernate.SQL: DEBUG
logging.level.org.springframework.transaction: DEBUG

spring.jpa.hibernate.ddl-auto: update

DATASOURCE_URL: jdbc:postgresql://localhost:5432/app
DATASOURCE_USERNAME: postgres
DATASOURCE_PASSWORD: admin123
KAFKA_BOOTSTRAP_SERVERS: localhost:9092
SCHEMA_REGISTRY_URL: http://localhost:8081
management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
